---
name: {{name}}
version: '0.1.0.0'
category: Text
author: {{author-name}}
maintainer: {{author-email}}
copyright: 2018 {{author-name}}
license: MIT
github: {{github-username}}/{{name}}
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && <5

ghc-options: -Wall

library:
  source-dirs: src

executables:
  {{name}}:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - {{name}}

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - {{name}}
