---
version: 2.0

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run:
          name: Digest
          command: |
            git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            # TODO: These lines are supposed to use double-braces, not parens,
            # but the stack template system chokes on them
            #
            # https://circleci.com/docs/2.0/caching/
            #
            # - v0-(( .Branch ))-(( checksum "digest" ))
            # - v0-(( .Branch ))-
            - v0-master-
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - save_cache:
          # TODO: This line is supposed to use double-braces, not parens, but
          # the stack template system chokes on it.
          #
          # https://circleci.com/docs/2.0/caching/
          #
          # key: v0-(( .Branch ))-(( checksum "digest" ))
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: make test
      - run:
          name: Lint
          command: make lint
